### ISSUE TITLE
Low level graphics API

### ISSUE THREAD

**Issue by jayrulez** [EvergineTeam/Vulkan.NET#6]
@jcant0n I haven't found another place where I can ask this question so I'll try here.

Would the Evergine team consider releasing the low level graphics API as open source?

It seems to make use of Veldrid which is also open source but has evolved a lot and added other platforms.

This would be very useful standalone or even as a contribution back to Veldrid.

**Comment by theFJ1991** [comment]
> @jcant0n I haven't found another place where I can ask this question so I'll try here.
> 
> Would the Evergine team consider releasing the low level graphics API as open source?
> 
> It seems to make use of Veldrid which is also open source but has evolved a lot and added other platforms.
> 
> This would be very useful standalone or even as a contribution back to Veldrid.

**Comment by jcant0n** [comment]
Hi,

The code is not an evolution from another code base, this was written from scrach. 
Maybe in the future we can open the source of this project, but for now the access to the project repository is under license that can be purchaged from here: https://evergine.com/download/

The engine is free to use and this is part of the business model right now.

Thanks for your comment.
